import type { Metadata } from 'next'

import localFont from 'next/font/local'

import '../styles'
import RootProvider from '../providers'

const inter = localFont({
  src: '../../../public/fonts/inter/Inter-VariableFont_opsz,wght.ttf',
  display: 'swap',
  fallback: ['system-ui'],
})

export const metadata: Metadata = {
  title: 'Framegram',
  description: 'Generated by create next app',
}

export function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <RootProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </RootProvider>
  )
}
